---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: geoip-pv
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100M
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: graylog
  name: geoip-pv-claim
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100M
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graylog-deployment
  # namespace: graylog
  labels:
    app: graylog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graylog
  template:
    metadata:
      labels:
        app: graylog
    spec:
      volumes:
      - name: graylog-settings-master
        configMap:
          name: graylog-settings-master
      - name: graylog-keystore
        configMap:
          name: graylog-keystore
      - name: geoip-database
        persistentVolumeClaim:
          claimName: geoip-pv-claim

      initContainers:
        - name: grant-permissions
          image: busybox
          securityContext:
            runAsUser: 0
          imagePullPolicy: "IfNotPresent"
          command:
          - 'sh'
          - '-c'
          - 'mkdir -p /geoip/data ; chown -R 1100:1100 /geoip/data/'
          
          volumeMounts:
          - name: geoip-database
            mountPath: /geoip


      containers:
      - name: graylog
        image: graylog/graylog:4.2.1-jre11
        
        # Add additional container ports for each input.
        ports:
          # Syslog UDP
        - containerPort: 5442
          protocol: UDP
        
        # Testing command to prevent the pod from dying while under development. 
        # command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
        command: ['sh', '-c', '/usr/share/graylog/bin/graylogctl run > /usr/share/graylog/log/graylog-server.log']
        
        # Resources request and limits still need fine tuning.
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "3Gi"
            cpu: "1.5"
        
        #Probes
        livenessProbe:
          exec:
            command:
              - /health_check.sh
          initialDelaySeconds: 99
          periodSeconds: 5
          failureThreshold: 3      
        startupProbe:
          exec:
            command:
              - /health_check.sh
          failureThreshold: 30
          periodSeconds: 10
        
        volumeMounts:
        # ConfigMaps
        - name: graylog-settings-master
          mountPath: /etc/graylog/server/
        - name: graylog-keystore
          # Uses openjdk 11 by default. Change the major release version number if using a deferent version of java.
          # Ex: /usr/local/openjdk-8/lib/security/
          mountPath: /usr/local/openjdk-11/lib/security/
        # Persistent Volume Claims
        - name: geoip-database
          mountPath: /geoip
        
        
      restartPolicy: Always     