---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: graylog-deployment
  # namespace: graylog
  labels:
    app: graylog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: graylog
  template:
    metadata:
      labels:
        app: graylog
    spec:
      containers:
      - name: graylog
        image: graylog/graylog:4.1-jre11
        # Testing command to prevent the pod from dying while under development. 
        # command: ['sh', '-c', 'echo "Hello, Kubernetes!" && sleep 3600']
        command: ['sh', '-c', '/usr/share/graylog/bin/graylogctl run']
        # Resources request and limits still need fine tuning.
        resources:
          requests:
            memory: "1Gi"
            cpu: "250m"
          limits:
            memory: "3Gi"
            cpu: "1.5"
        volumeMounts:
        - name: graylog-settings
          mountPath: /etc/graylog/server/
        - name: graylog-keystore
        # Uses openjdk 11 by default. Change the major release version number if using a deferent version of java.
        # Ex: /usr/local/openjdk-8/lib/security/
          mountPath: /usr/local/openjdk-11/lib/security/
        
        livenessProbe:
          exec:
            command:
              - /health_check.sh
          initialDelaySeconds: 99
          periodSeconds: 5
          failureThreshold: 1
        
        startupProbe:
          exec:
            command:
              - /health_check.sh
          failureThreshold: 30
          periodSeconds: 10
        
      restartPolicy: Always     
      volumes:
      - name: graylog-settings
        configMap:
          name: graylog-settings
      - name: graylog-keystore
        configMap:
          name: graylog-keystore