apiVersion: v1
kind: Service
metadata:
  labels:
    app: graylog
  name: graylog-deployment-svc
spec:
  selector:
    app: graylog
  type: ClusterIP
  ports:
    - name: graylog-http-port
      port: 9000
      protocol: TCP
      targetPort: 9000
