apiVersion: v1
kind: Pod
metadata:
  name: graylogutils
spec:
  containers:
  - name: graylogutils
    image: benihelputech/graylogtester:latest
    command:
      - sleep
      - "3600"
    imagePullPolicy: IfNotPresent
  restartPolicy: Always